title: Stackbit Fjord Theme
baseURL: /
params:
  palette: yellow
  header:
    title: Fjord
    tagline: 'Não parar, não precipitar, não retroceder.'
    logo_img: images/logo.svg
    logo_img_alt: Fjord Logo
    background_img: images/header-bg.jpg
    has_nav: true
    nav_links:
      - label: Início
        url: /inicio
        style: link
      - url: /sobre
        style: link
        label: Sobre
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Contato
        url: /contato
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: linkedin
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://marvelous-apple-8d004.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
